### ISSUE TITLE
Walrus operator in sankeyflow.py isn't compatible with python 3.7 or 3.6

### ISSUE THREAD

**Issue by Bitte1Bit** [riley-x/SankeyFlow#2]
The use of the Walrus-operator ( "x :=" in line 73) is just possible by python 3.8 or higher versions. As you stated sankey flow is compatible with python 3.6 ore higher, please change code or project description under https://pypi.org/project/sankeyflow/#description (there the minimum version number for python is 3.6).

Thanks in advance :-)

**Comment by riley-x** [comment]
Thanks for the catch, fixed in 5a8562a2951d5f4ac2084d7b5781f73d950cfeb4
