### ISSUE TITLE
ValueError: Bad flow - flow is backwards

### ISSUE THREAD

**Issue by naustica** [riley-x/SankeyFlow#3]
Hi,

i have the following error: ValueError: Bad flow - flow is backwards: ('Book', 'Book', 18)

flows = [('book series', 'Book', 18),
 ('Book', 'Book', 18),
 ('book series', 'Book', 458),
 ('Book', 'Book in series', 458),
 ('book series', 'Book Series', 380),
 ('Book Series', 'Book', 380),
 ('book series', 'Book Series', 223909),
 ('Book Series', 'Book in series', 223909),
 ('book series', 'Book Series', 3),
 ('Book Series', 'Journal', 3),
 ('book series', 'Conference Proceeding', 76),
 ('Conference Proceeding', 'Book', 76),
 ('book series', 'Conference Proceeding', 13119),
 ('Conference Proceeding', 'Book in series', 13119),
 ('book series', 'Journal', 311),
 ('Journal', 'Book in series', 311),
 ('book series', 'Journal', 90),
 ('Journal', 'Journal', 90),
 ('book series', None, 2),
 (None, 'Book in series', 2),
 ('conference', 'Book', 36),
 ('Book', 'Book in series', 36),
 ('conference', 'Book Series', 1242),
 ('Book Series', 'Book in series', 1242),
 ('conference', 'Conference Proceeding', 33249),
 ('Conference Proceeding', 'Book', 33249),
 ('conference', 'Conference Proceeding', 140028),
 ('Conference Proceeding', 'Book in series', 140028),
 ('conference', 'Conference Proceeding', 4),
 ('Conference Proceeding', 'Journal', 4),
 ('conference', 'Journal', 22),
 ('Journal', 'Book in series', 22),
 ('conference', 'Journal', 19),
 ('Journal', 'Journal', 19),
 ('ebook platform', 'Book', 1880),
 ('Book', 'Book', 1880),
 ('ebook platform', 'Book', 671),
 ('Book', 'Book in series', 671),
 ('ebook platform', 'Book', 16),
 ('Book', 'Journal', 16),
 ('ebook platform', 'Book Series', 225),
 ('Book Series', 'Book', 225),
 ('ebook platform', 'Book Series', 59346),
 ('Book Series', 'Book in series', 59346),
 ('ebook platform', 'Conference Proceeding', 2001),
 ('Conference Proceeding', 'Book', 2001),
 ('ebook platform', 'Conference Proceeding', 5186),
 ('Conference Proceeding', 'Book in series', 5186),
 ('ebook platform', 'Journal', 136),
 ('Journal', 'Book in series', 136),
 ('ebook platform', 'Journal', 59),
 ('Journal', 'Journal', 59),
 ('ebook platform', None, 2),
 (None, 'Book in series', 2),
 ('journal', 'Book', 139),
 ('Book', 'Book in series', 139),
 ('journal', 'Book', 555),
 ('Book', 'Journal', 555),
 ('journal', 'Book Series', 1),
 ('Book Series', 'Book', 1),
 ('journal', 'Book Series', 123675),
 ('Book Series', 'Book in series', 123675),
 ('journal', 'Book Series', 14245),
 ('Book Series', 'Journal', 14245),
 ('journal', 'Conference Proceeding', 2107),
 ('Conference Proceeding', 'Book', 2107),
 ('journal', 'Conference Proceeding', 348045),
 ('Conference Proceeding', 'Book in series', 348045),
 ('journal', 'Conference Proceeding', 49024),
 ('Conference Proceeding', 'Journal', 49024),
 ('journal', 'Journal', 241),
 ('Journal', 'Book', 241),
 ('journal', 'Journal', 11562),
 ('Journal', 'Book in series', 11562),
 ('journal', 'Journal', 20072071),
 ('Journal', 'Journal', 20072071),
 ('journal', 'Trade Journal', 5),
 ('Trade Journal', 'Book in series', 5),
 ('journal', 'Trade Journal', 11504),
 ('Trade Journal', 'Journal', 11504),
 ('journal', None, 3),
 (None, 'Book in series', 3),
 ('journal', None, 4327),
 (None, 'Journal', 4327),
 ('repository', 'Book', 14),
 ('Book', 'Book in series', 14),
 ('repository', 'Book Series', 1324),
 ('Book Series', 'Book in series', 1324),
 ('repository', 'Book Series', 4),
 ('Book Series', 'Journal', 4),
 ('repository', 'Conference Proceeding', 68),
 ('Conference Proceeding', 'Book', 68),
 ('repository', 'Conference Proceeding', 174),
 ('Conference Proceeding', 'Book in series', 174),
 ('repository', 'Conference Proceeding', 352),
 ('Conference Proceeding', 'Journal', 352),
 ('repository', 'Journal', 1),
 ('Journal', 'Book', 1),
 ('repository', 'Journal', 876),
 ('Journal', 'Book in series', 876),
 ('repository', 'Journal', 33842),
 ('Journal', 'Journal', 33842),
 ('repository', 'Trade Journal', 1),
 ('Trade Journal', 'Journal', 1),
 ('repository', None, 1),
 (None, 'Journal', 1)]

Can you help me with this?

Best, Nick

**Comment by riley-x** [comment]
Sankeyflow can't handle backwards flows, i.e. those that move from right to left. That includes circular flows, those that start and end at the same node. 

Also, your input has a ton of duplicated and redundant entries, including several entries with `None`, which will also cause problems.
